### ISSUE TITLE
First Image error

### ISSUE THREAD

**Issue by gbowman85** [PremiumPresta/export-products-for-csv-import-prestashop-1.6#2]
Thanks so much for providing this override and also for your explanation. 

I had a issue where the first image for every product would fail. It comes out as url.com/shop/img//85-413.jpg where it should be something like url.com/shop/img/p/4/1/0/410.jpg

I worked around it by removing the override and exporting using the usual export method and then merging the data manually.

**Comment by gabdara** [comment]
Hi,

Can you tell me on what version of PrestaShop this happen and also if you have previously upgraded from an older version? Are there other overrides in place that could change the URL format?

Thank you for your feedback

**Comment by gbowman85** [comment]
1.6.1.11
Recently update using the one click update from version 1.6.1.1 (I think, maybe 1.6.1.4).
Don't think there's any other overrides.

**Comment by a-mazed** [comment]
Hi Gabriel!
Thank you for this nice tool!
But I have the same problem as gbowman85
PrestaShop version 1.6.1.11
Export file looks like
![default](https://cloud.githubusercontent.com/assets/25726917/22865029/c5d22132-f16c-11e6-9819-91150cbd0e94.png)

**Comment by bgmastermind** [comment]
same here on 1.6.1.11

**Comment by cmderks93** [comment]
Same here on 1.6.1.11, also will do the manual image merge. Overall an nice tool

**Comment by gabdara** [comment]
Thanks for the feedback guys!
I've just committed a fix for this.
Let me know if it's working fine now, otherwise feel free to reopen the issue.

**Comment by cmderks93** [comment]
Works perfectly! Now I can pull 17000 items 👍
