### ISSUE TITLE
Does it works on PS 1.7.2?

### ISSUE THREAD

**Issue by karopka** [PremiumPresta/export-products-for-csv-import-prestashop-1.6#4]
Hello!

I have add your override to my site on PS 1.7.2 and clear cache. 
In class_index.php now correct path to the file:
```
  'AdminProductsController' => 
  array (
    'path' => 'override/controllers/admin/AdminProductsController.php',
    'type' => 'class',
    'override' => false,
  ),
```
But when I get the export file it is still standart PS file without any new fields.

**Comment by karopka** [comment]
It's seems that exportAction function now in this file:
\src\PrestaShopBundle\Controller\Admin\ProductController.php

**Comment by gabdara** [comment]
Hi,

This override works only with 1.6 versions.
The admin product page code has changed completely in 1.7.

**Comment by karopka** [comment]
Do you have plans to write override for 1.7.x version? :)

**Comment by gabdara** [comment]
An override wouldn't work in this case for 1.7.
I would have to think of another approach.
